[package]
name = "input_json"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "generate_input_json"
path = "src/generate_input_json.rs"

[dependencies]
binascii = "0.1"
clap = { version = "3.1.8", features = ["derive"] }
